name: butler

on:
  issue_comment:
    types:
      - created

permissions:
  issues: write
  pull-requests: write

jobs:
  chat:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.comment.body }}
      - uses: ca-dp/code-butler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          cmd: chat
          comment_body: ${{ github.event.comment.body }}
